# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brach_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('rating', models.IntegerField(max_length=50)),
                ('branch', models.ManyToManyField(to='crud.Branch')),
                ('brands', models.ManyToManyField(to='crud.Brands')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Products')),
            ],
        ),
    ]
